import * as path from 'path';

/**
 * Maps preprocessed file paths (after AUTOSAR macro normalization) back to
 * original source files. Also resolves workspace-relative paths.
 */
export class PathMapper {
  private mappings = new Map<string, string>();
  private workspaceRoot: string;

  constructor(workspaceRoot: string) {
    this.workspaceRoot = workspaceRoot;
  }

  /**
   * Register a mapping from preprocessed path to original path.
   * Used when AUTOSAR macros are expanded before indexing.
   */
  registerMapping(preprocessedPath: string, originalPath: string): void {
    this.mappings.set(this.normalize(preprocessedPath), originalPath);
  }

  /**
   * Load mappings from a JSON file generated by the preprocessor.
   * Format: { "preprocessed/path.c": "original/path.c", ... }
   */
  async loadMappingsFromFile(mappingFilePath: string): Promise<void> {
    const fs = await import('fs');
    try {
      const content = await fs.promises.readFile(mappingFilePath, 'utf-8');
      const mappings = JSON.parse(content) as Record<string, string>;
      for (const [pre, orig] of Object.entries(mappings)) {
        this.registerMapping(pre, orig);
      }
    } catch {
      // No mapping file — paths pass through unchanged
    }
  }

  /**
   * Resolve a path from GitNexus results to the actual file on disk.
   * Tries: mapping table → absolute path → workspace-relative → unchanged.
   */
  resolve(filePath: string): string {
    // Check mapping table first
    const normalized = this.normalize(filePath);
    const mapped = this.mappings.get(normalized);
    if (mapped) {
      return this.toAbsolute(mapped);
    }

    // Already absolute?
    if (path.isAbsolute(filePath)) {
      return filePath;
    }

    // Workspace-relative
    return this.toAbsolute(filePath);
  }

  /**
   * Convert to absolute via workspace root.
   */
  private toAbsolute(filePath: string): string {
    if (path.isAbsolute(filePath)) { return filePath; }
    return path.join(this.workspaceRoot, filePath);
  }

  /**
   * Normalize path separators for consistent mapping.
   */
  private normalize(p: string): string {
    return p.replace(/\\/g, '/');
  }

  /**
   * Make a path relative to the workspace root.
   */
  toRelative(filePath: string): string {
    return path.relative(this.workspaceRoot, filePath);
  }

  /**
   * Shorten a path for display: extract last 2 segments.
   */
  static shortDisplay(filePath: string): string {
    const parts = filePath.replace(/\\/g, '/').split('/');
    return parts.length > 2 ? parts.slice(-2).join('/') : filePath;
  }
}
